steps:
  - label: 'check-cabal-project'
    command: 'nix-build ./nix -A iohkNix.checkCabalProject -o check-cabal-project.sh && ./check-cabal-project.sh'
    agents:
      system: x86_64-linux

  - label: 'stack-cabal-sync'
    command: 'nix-shell ./nix -A iohkNix.stack-cabal-sync-shell --run .buildkite/stack-cabal-sync.sh'
    agents:
      system: x86_64-linux

  - label: 'Validate OpenAPI Specification'
    command:
      - 'nix-shell --run "openapi-spec-validator --schema 2.0 explorer-api/swagger.yaml"'
      - 'nix-shell --run "openapi-spec-validator --schema 2.0 submit-api/swagger.yaml"'
    agents:
      system: x86_64-linux

  - label: 'Docker Images'
    command:
      - "nix-build .buildkite/docker-build-push.nix -o docker-build-push"
      - "./docker-build-push"
    branches: master
    agents:
      system: x86_64-linux
